### PR TITLE
Refactors Hedgehog Generator module (and many other things)

### PR DESCRIPTION
**Pull request by jkachmar**
This PR got away from me, and I'm more than willing to break it up into smaller chunks if that would help folks review it.

There are three major changes being introduced here:
1. Added a `hedgehog` flag that can be used to toggle the `hedgehog` dependency and exported module
2. Reworked `graphql-parser.cabal` to enable a much more comprehensive set of warnings/errors
    - As part of this, I've also formatted the `graphql-parser.cabal` file with `cabal-fmt` and the project with `ormolu`
3. Swapped `criterion` for `tasty-bench` in the benchmarks (`tasty-bench` has a much lighter dependency footprint)

### CODE REVIEW

**Comment by jkachmar** [comment]
Closes #48.

**Comment by abooij** [comment]
Oof yeah this is a lot.

The organisation of the work into various commits helps. I think for me it would help if we first had a PR which only, purely, applied tool-based formatting, and nothing else - perhaps not even changed imports/exports. I'd be willing to trust that change with only a very cursory review, and it should reduce the diff size significantly.

**Comment by jkachmar** [comment]
Opened #58 which just contains the formatting changes.

**Comment by jkachmar** [comment]
Most of the non-generators work has been done in other PRs. I'll close this and we can reopen something that more directly targets #48 in the future.

**Pull request closed without merging**
