### PR TITLE
Add a Nix flake to provide tooling and build the library.

### PR DESCRIPTION
**Pull request by SamirTalwar**
The flake.lock file is copied from hasura/graphql-engine to keep things
simpler (for me, at least).

This is all optional and opt-in, typically by adding a .envrc.local file
containing `use flake`.

### CODE REVIEW

**Comment by plcplc** [comment]
When I go `nix shell` I don't get `cabal` or `ormolu` in my path.. the `flake.nix` file suggests I should.

**Comment by SamirTalwar** [comment]
@plcplc: You need to run `nix develop --impure`; `nix-shell` doesn't work with flakes unless we provide a little hack along the lines of:

_shell.nix_:

```nix
{ system ? builtins.currentSystem }:

(builtins.getFlake (toString ./.)).devShells.${system}
```

I've just pushed this to make life easier for people.

**Comment by plcplc** [comment]
.. Or the other way around, with `flake.nix` importing `shell.nix`, as is how graphql-engine is setup.

**Comment by plcplc** [comment]
Thanks - that had confused me a bit.

**Comment by SamirTalwar** [comment]
It's a little more complicated in the graphql-engine setup (which is currently private but I'm up for pushing this to the open-source repository): _flake.nix_ imports _nix/shell.nix_, and _shell.nix_ imports _flake.nix_.

_nix/shell.nix_ defines the shell, expecting nixpkgs to be provided as an argument; _flake.nix_ provisions the correct (locked) version of nixpkgs, and _shell.nix_ is exactly as above.

**Review by plcplc — APPROVED** [review]
I didn't test the envrc as I'm not a user of that myself.

But I can do `nix develop` and `cabal build` in the resulting shell, and I can do `nix build` and everythings builds. So I'm happy with that.

**Comment by SamirTalwar** [comment]
Awesome, then I think we're good to go. Thank you!

**Pull request merged**
